### ISSUE TITLE
changes in area for states not along the border

### ISSUE THREAD

**Issue by ecv19** [sjsrey/geoplanar#23]
encountering the issue where area changes in the interior states for both mex and us

https://github.com/ecv19/geoplanar/blob/main/notebooks/usmex_level1_changes.ipynb

**Comment by sjsrey** [comment]
Need more specifics on how the input data to that notebook were created? What geoplanar operations in what order? Is there a link to a notebook that proceeds this one?

**Comment by ecv19** [comment]
notebooks Workflow:

1.  https://github.com/ecv19/geoplanar/blob/main/notebooks/data_processing_1.ipynb   for input data
2. https://github.com/ecv19/geoplanar/blob/main/notebooks/usmex_level1.ipynb. for geoplanar 
3. https://github.com/ecv19/geoplanar/blob/main/notebooks/usmex_level1_changes.ipynb for changes

**Comment by sjsrey** [comment]
I think it is a (spurious) precision issue:

![image](https://user-images.githubusercontent.com/118042/149038856-4a6f86df-80e0-4459-9b0a-151309c912d4.png)

[Source](https://xkcd.com/2170/)

**Comment by ecv19** [comment]
so, we were overthinking this. doesn't hurt to check though.

**Comment by sjsrey** [comment]
> so, we were overthinking this. doesn't hurt to check though.

Exactly.
