### ISSUE TITLE
cartographic simplification function?

### ISSUE THREAD

**Issue by knaaptime** [sjsrey/geoplanar#61]
it's common for me to work on notebooks of large study areas with lots of complex polygons (e.g. census blockgroups at a metropolitan scale), where you don't really need the fine-grained geographic resolution, and rendering all those vertices means you can only fire off one or two `explore`s before the browser crashes out. So, I've found geoplanar useful for doing a crude cartographic simplification where you use geopandas to simplify the geoms then geoplanar to re-planarize the geoms so nothing looks crazy. Something like this

```python
def simplify_planar(gdf, tolerance, overlap_kwds=None, fill_kwds=None):
    if overlap_kwds is None:
        overlap_kwds = dict()
    if fill_kwds is None:
        fill_kwds = dict()

    gdf = gdf.copy()
    gdf["geometry"] = gdf.geometry.simplify(tolerance)
    gdf = geoplanar.fill_gaps(gdf, **fill_kwds)
    gdf = geoplanar.trim_overlaps(gdf, **overlap_kwds)
    return gdf
```

curious if this kind of convenience function would be useful here or elsewhere

(note the order of ops matters; you need to fill gaps before trimming overlaps because the reverse ends up in lots of overlaps)

**Comment by martinfleis** [comment]
Given the coverage simplification exposed from GEOS should come in the shapely 2.1, this may be needed only for a short time in the meantime? Also, there's `topojson`'s implementation as well. I am not certain how reliable this is, there are likely many uncaught corner cases here.

**Comment by knaaptime** [comment]
im not too worried about corner cases since this is only for display rather than analysis but I didn't know about the shapely change. I'd forgotten about topojson, but that's still not ideal either because i'd like to do everything in the same code flow

**Comment by knaaptime** [comment]
closing assuming [this](https://libgeos.org/doxygen/classgeos_1_1simplify_1_1TopologyPreservingSimplifier.html) will eventually be a geoseries method or something
